# Generated by Django 3.2.5 on 2021-07-10 14:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210702_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlesorder',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='detailorderassociatedcompany',
            name='partner_code',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='detailorderassociatedcompany',
            name='reference',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('[A-Za-z]{2}[0-9]$', 'Formato de referencia incorrecto')]),
        ),
        migrations.AlterField(
            model_name='detailorderbranchoffice',
            name='branch_office_code',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='detailorderbranchoffice',
            name='reference',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('[A-Za-z]{2}[0-9]$', 'Formato de referencia incorrecto')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='deliver_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
